#! /bin/sh
# Updates the gtk.immodules in /usr/lib*/gtk-2.0/*/immodules.cache

umask 022

# Get the machine type from uname:
host=$(uname -m)

case "${host}" in
  s390x|x86_64)
   if [ -x /usr/bin/gtk-query-immodules-2.0-64 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating gtk.immodules for ${host}:"
       echo "  /usr/bin/gtk-query-immodules-2.0-64 --update-cache"
     fi
     /usr/bin/gtk-query-immodules-2.0-64 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating gtk.immodules for ${host}:"
       echo "  /usr/bin/gtk-query-immodules-2.0 --update-cache"
     fi
     /usr/bin/gtk-query-immodules-2.0 --update-cache
   fi
   ;;
  *)
   if [ -x /usr/bin/gtk-query-immodules-2.0-32 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating gtk.immodules for ${host}:"
       echo "  /usr/bin/gtk-query-immodules-2.0-32 --update-cache"
     fi
     /usr/bin/gtk-query-immodules-2.0-32 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating gtk.immodules for ${host}:"
       echo "  /usr/bin/gtk-query-immodules-2.0 --update-cache"
     fi
     /usr/bin/gtk-query-immodules-2.0 --update-cache
   fi
   ;;
esac
