.\" Copyright 2009 Red Hat, Inc.
.TH segregdomain 1 2009-10-16 "CRDA" "User Commands"
.SH NAME
setregdomain \- set regulatory domain based on timezone
.SH SYNOPSIS               
.B setregdomain                  
.SH DESCRIPTION
setregdomain sets the regulatory domain for your system; it takes no
arguments and is normally called via system script (eg, udev) rather
than manually by an adminstrator.
.SH "SEE ALSO"
.BR iw (1)
