#! /bin/sh
# Updates the pango.modules in /usr/lib*/pango/*/modules

umask 022

# Get the machine type from uname:
host=$(uname -m)
file=/usr/lib/pango/pango.modules

case "${host}" in
  s390x|x86_64)
   if [ -d /usr/lib64/pango ] ;then
     file=/usr/lib64/pango/pango.modules
   fi
   if [ -x /usr/bin/pango-querymodules-64 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating pango.modules for ${host} arch:"
       echo "  /usr/bin/pango-querymodules-64 \\"
       echo "  > ${file}"
     fi
     /usr/bin/pango-querymodules-64 > ${file}
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating pango.modules for ${host} arch:"
       echo "  /usr/bin/pango-querymodules \\"
       echo "  > ${file}"
     fi
     /usr/bin/pango-querymodules > ${file}
   fi
   ;;
  *)
   if [ -x /usr/bin/pango-querymodules-32 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating pango.modules for ${host} arch:"
       echo "  /usr/bin/pango-querymodules-32 \\"
       echo "  > ${file}"
     fi
     /usr/bin/pango-querymodules-32 > ${file}
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating pango.modules for ${host} arch:"
       echo "  /usr/bin/pango-querymodules \\"
       echo "  > ${file}"
     fi
     /usr/bin/pango-querymodules > ${file}
   fi
   ;;
esac

