#! /bin/sh
# Updates the pango.modules in /usr/lib*/pango/*/modules.cache

umask 022

# Get the machine type from uname:
host=$(uname -m)

case "${host}" in
  s390x|x86_64)
   if [ -x /usr/bin/pango-querymodules-64 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating modules.cache for ${host}:"
       echo "  /usr/bin/pango-querymodules-64 --update-cache"
     fi
     /usr/bin/pango-querymodules-64 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating modules.cache for ${host}:"
       echo "  /usr/bin/pango-querymodules --update-cache"
     fi
     /usr/bin/pango-querymodules --update-cache
   fi
   ;;
  *)
   if [ -x /usr/bin/pango-querymodules-32 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating modules.cache for ${host}:"
       echo "  /usr/bin/pango-querymodules-32 --update-cache"
     fi
     /usr/bin/pango-querymodules-32 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating modules.cache for ${host}:"
       echo "  /usr/bin/pango-querymodules --update-cache"
     fi
     /usr/bin/pango-querymodules --update-cache
   fi
   ;;
esac
