#!/bin/sh
#-- alienkdehelper for alien --
# Script by Phantom X <megaphantomx@bol.com.br>
#--
# Copyright 2006, 2010 Phantom X, Goias, Brasil.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR `AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ALIENBIN="_BINDIR/alien"

XDIR="$1"
XFILE="$2"

if [ -z "${XDIR}" ]; then
  exit 1
fi

if [ -z "${XFILE}" ]; then
  exit 1
fi

if [ -x /usr/bin/zenity ]; then
  ZENITYBIN=/usr/bin/zenity
else
  echo 'zenity is missing!'
  exit 1
fi

if ! [ -r "${XFILE}" ] ;then
  ${ZENITYBIN} --title='Error!' --error --text="${XFILE} don't have read permissions\!"
  exit 1
fi

extractpops() {
  if [ ${RETVAL} -eq 0 ]; then
    ${ZENITYBIN} --title='Extraction completed!' --notification --text="Extracted to ${XDIR}."
  else
    ${ZENITYBIN} --title='Error in extraction!' --error --text="${XFILE} couldn't be extracted.\n The files that could be extracted are mantained in ${XDIR}"
  fi
}

if [ -r "${XDIR}" ]; then
  if [ -w "${XDIR}" ]; then
    cd "${XDIR}"
    ${ALIENBIN} -rgc "${XFILE}"
    RETVAL=$?
    extractpops
  else
    ${ZENITYBIN} --title='Warning!' --question --text="Directory do not have write permission.\n Do you want to extract in ${HOME}?"
    RETVAL2=$?
    if [ ${RETVAL2} -eq 0 ] ;then
      cd ${HOME}
      export XDIR=${HOME}
      ${ALIENBIN} -rgc "${XFILE}"
      RETVAL=$?
      extractpops
    fi
  fi
fi
