#!/bin/sh

# This script prepares configuration and run qbittorrent as user

exec="/usr/bin/qbittorrent-nox"
homedir="/var/lib/qbittorrent"

[ -x ${exec} ] || exit 1

unset DAEMON_USER
unset DAEMON_PORT
[ -e /etc/default/qbittorrent ] && . /etc/default/qbittorrent
DAEMON_USER=${DAEMON_USER:-qbittorrent:qbittorrent}
DAEMON_PORT=${DAEMON_PORT:-8080}

checkconfig() {
  if [[ "${DAEMON_USER}" == "" ]] ; then
    echo "Please edit /etc/default/qbittorrent"
    echo "You have to specify a user to run qbittorrent as, as we will not run it as root!"
    echo "Modify DAEMON_USER to your needs (you can also add a group, after a colon)"
    return 1
  fi
  if ! $(getent passwd | cut -d ':' -f 1 | grep $( echo "${DAEMON_USER}" | cut -d ':' -f 1 ) -sq) ; then
    echo "Please edit /etc/default/qbittorrent"
    echo "Your user has to exist!"
    return 2
  fi
  unset DAEMON_OUSER
  DAEMON_OUSER=$(echo ${DAEMON_USER} | cut -d ':' -f 1)
  if [[ "${DAEMON_OUSER}" == "root" ]] ; then
    echo "Please edit /etc/default/qbittorrent"
    echo "Do not use root as user!"
    return 3
  fi
  unset DAEMON_GROUP
  echo "${DAEMON_USER}" | grep ':' -sq && DAEMON_GROUP=$( echo ${DAEMON_USER} | cut -d ':' -f 2 )
  if [ -n "${DAEMON_GROUP}" ] && ! $(cut -d ':' -f 1 /etc/group | grep "${DAEMON_GROUP}" -sq) ; then
    echo "Please edit /etc/default/qbittorrent"
    echo "Your group has to exist too!"
    return 4
  fi
  DAEMON_USER_HOME=$(getent passwd | grep ^$( echo "${DAEMON_USER}" | cut -d ':' -f 1 ): | cut -d ':' -f 6)
  return 0
}

checkconfig || exit $?

if [[ "${DAEMON_OUSER}" == "qbittorrent" ]] && [[ -d "${homedir}" ]];then
  chown -R qbittorrent.qbittorrent "${homedir}"
fi

exec /bin/su - "${DAEMON_OUSER}" -s /bin/sh -c "${exec} --webui-port=${DAEMON_PORT}"
