#!/bin/sh

# Determine the version of the running kernel:
RELEASE=$(uname -r)

### Update module dependencies ###
# If /usr is mounted and we have 'find', we can try to take a shortcut:
if [ -x /usr/bin/find -a -e /lib/modules/$RELEASE/modules.dep \
     -a /lib/modules/${RELEASE}/modules.dep -nt /etc/modules.conf ]; then
  NEWMODS="$(/usr/bin/find /lib/modules/${RELEASE} -mindepth 2 -type f -newer /lib/modules/${RELEASE}/modules.dep)"
  # Only rebuild dependencies if new module(s) are found:
  if [ ! "" = "${NEWMODS}" ]; then
    echo "Updating module dependencies for Linux $RELEASE:"
    /sbin/depmod -a
  else
    echo "Module dependencies up to date (no new kernel modules found)."
  fi
else # we don't have find, or there is no existing modules.dep, or it is out of date.
  echo "Updating module dependencies for Linux ${RELEASE}:"
  /sbin/depmod -A
fi
