# slack-artwork Makefile

# Copyright (C) 2008 Phantom X, Goiania, Brazil.
# This Makefile.in is free software; the author
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL=/bin/sh

PACKAGE = slack-artwork

srcdir = .
top_srcdir = .
subdir = .

all:
	make dist -C $(srcdir)/slack-artwork
	mv $(PACKAGE)/$(PACKAGE)*.tar.bz2 .

.NOEXPORT:
