# dotnew-pt_BR Makefile

# Copyright (C) 2012 Phantom X, Goiania, Brazil.
# This Makefile is free software; the author
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL=/bin/sh

PACKAGE = dotnew-pt_BR

srcdir = .
top_srcdir = .
subdir = .

all:
	gzip -9c $(PACKAGE).po > $(PACKAGE).po.gz

.NOEXPORT:
