#!/bin/sh

# This script prepares configuration and run mpd as user

exec="/usr/bin/znc"
homedir="/var/lib/znc"

[ -x ${exec} ] || exit 1

nset ZNC_USER
[ -e /etc/default/znc ] && . /etc/default/znc
ZNC_USER=${ZNC_USER:-znc:znc}

checkconfig() {
  if [[ "${ZNC_USER}" == "" ]] ; then
    echo "Please edit /etc/default/znc"
    echo "You have to specify a user to run znc as, as we will not run it as root!"
    echo "Modify ZNC_USER to your needs (you can also add a group, after a colon)"
    return 1
  fi
  if ! $(getent passwd | cut -d ':' -f 1 | grep $( echo "${ZNC_USER}" | cut -d ':' -f 1 ) -sq) ; then
    echo "Please edit /etc/default/znc"
    echo "Your user has to exist!"
    return 1
  fi
  ZNC_OUSER=$(echo ${ZNC_USER} | cut -d ':' -f 1)
  if [[ "${ZNC_USER}" == "root" ]] ; then
    echo "Please edit /etc/default/znc"
    echo "Do not use root as user!"
    return 1
  fi
  unset ZNC_GROUP
  echo "${ZNC_USER}" | grep ':' -sq && ZNC_GROUP=$( echo ${ZNC_USER} | cut -d ':' -f 2 )
  if [ -n "${ZNC_GROUP}" ] && ! $(cut -d ':' -f 1 /etc/group | grep "${ZNC_GROUP}" -sq) ; then
    echo "Please edit /etc/default/znc"
    echo "Your group has to exist too!"
    return 1
  fi
  ZNC_USER_HOME=$(getent passwd | grep ^$( echo "${ZNC_USER}" | cut -d ':' -f 1 ): | cut -d ':' -f 6)
  ZNC_USER_CONFIG="${ZNC_USER_HOME}/.znc"
  if ! [[ -e "${ZNC_USER_CONFIG}/configs/znc.conf" ]] ; then
    echo "${ZNC_USER_CONFIG}/configs/znc.conf is missing"
    echo "Run 'su - ${ZNC_OUSER} -s /bin/sh -c \"${exec} --makeconf\"' and try again"
    return 2
  fi
  return 0
}

checkconfig || exit $?

if [[ "${DELUGED_OUSER}" == "znc" ]] && [[ -d "${homedir}" ]];then
  chown -R znc.znc "${homedir}"
fi

exec /bin/su - "${ZNC_OUSER}" -s /bin/sh -c "${exec}"
