diff -ur java_libs.orig/com/lowagie/bc/asn1/Makefile java_libs/com/lowagie/bc/asn1/Makefile
--- java_libs.orig/com/lowagie/bc/asn1/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/bc/asn1/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/Makefile java_libs/com/lowagie/text/Makefile
--- java_libs.orig/com/lowagie/text/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,8 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
+
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/markup/Makefile java_libs/com/lowagie/text/markup/Makefile
--- java_libs.orig/com/lowagie/text/markup/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/markup/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/pdf/codec/Makefile java_libs/com/lowagie/text/pdf/codec/Makefile
--- java_libs.orig/com/lowagie/text/pdf/codec/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/pdf/codec/Makefile	2010-05-31 12:32:20.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/pdf/codec/postscript/Makefile java_libs/com/lowagie/text/pdf/codec/postscript/Makefile
--- java_libs.orig/com/lowagie/text/pdf/codec/postscript/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/pdf/codec/postscript/Makefile	2010-05-31 12:31:20.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/pdf/codec/wmf/Makefile java_libs/com/lowagie/text/pdf/codec/wmf/Makefile
--- java_libs.orig/com/lowagie/text/pdf/codec/wmf/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/pdf/codec/wmf/Makefile	2010-05-31 12:32:39.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/pdf/fonts/Makefile java_libs/com/lowagie/text/pdf/fonts/Makefile
--- java_libs.orig/com/lowagie/text/pdf/fonts/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/pdf/fonts/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -21,6 +21,8 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
+
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/pdf/Makefile java_libs/com/lowagie/text/pdf/Makefile
--- java_libs.orig/com/lowagie/text/pdf/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/pdf/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/com/lowagie/text/xml/xmp/Makefile java_libs/com/lowagie/text/xml/xmp/Makefile
--- java_libs.orig/com/lowagie/text/xml/xmp/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/com/lowagie/text/xml/xmp/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,8 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
+
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/gnu/gcj/convert/Makefile java_libs/gnu/gcj/convert/Makefile
--- java_libs.orig/gnu/gcj/convert/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/gnu/gcj/convert/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/gnu_local/java/security/Makefile java_libs/gnu_local/java/security/Makefile
--- java_libs.orig/gnu_local/java/security/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/gnu_local/java/security/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/gnu_local/java/security/provider/Makefile java_libs/gnu_local/java/security/provider/Makefile
--- java_libs.orig/gnu_local/java/security/provider/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/gnu_local/java/security/provider/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,8 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
+
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
diff -ur java_libs.orig/java_local/security/Makefile java_libs/java_local/security/Makefile
--- java_libs.orig/java_local/security/Makefile	2010-05-31 12:14:37.000000000 +0200
+++ java_libs/java_local/security/Makefile	2010-05-31 12:28:41.000000000 +0200
@@ -17,6 +17,7 @@
 
 %.o : %.java
 	$(GCJ) $(GCJFLAGS) -c $< -o $@
+	objcopy -L '_ZGr8_$$_dummy' $@
 
 %.class : %.java
 	$(GCJ) $(GCJFLAGS) -C $<
