#! /bin/sh
# Updates the loaders.cache in /usr/lib*/gdk-pixbuf-2.0/2.10.0/loaders.cache

umask 022

# Get the machine type from uname:
host=$(uname -m)

case "${host}" in
  s390x*|x86_64*)
   if [ -x /usr/bin/gdk-pixbuf-query-loaders-64 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating loaders.cache for ${host}:"
       echo "  /usr/bin/gdk-pixbuf-query-loaders-64 --update-cache"
     fi
     /usr/bin/gdk-pixbuf-query-loaders-64 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating loaders.cache for ${host}:"
       echo "  /usr/bin/gdk-pixbuf-query-loaders --update-cache"
     fi
     /usr/bin/gdk-pixbuf-query-loaders --update-cache
   fi
   ;;
  *)
   if [ -x /usr/bin/gdk-pixbuf-query-loaders-32 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating loaders.cache for ${host}:"
       echo "  /usr/bin/gdk-pixbuf-query-loaders-32 --update-cache"
     fi
     /usr/bin/gdk-pixbuf-query-loaders-32 --update-cache
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating loaders.cache for ${host}:"
       echo "  /usr/bin/gdk-pixbuf-query-loaders --update-cache"
     fi
     /usr/bin/gdk-pixbuf-query-loaders --update-cache
   fi
   ;;
esac
