#!/bin/sh

# This script prepares configuration and run transmission as user

exec="/usr/bin/transmission-daemon"
homedir="/var/lib/transmission"

[ -x ${exec} ] || exit 1

unset DAEMON_USER
unset DAEMON_PORT
[ -e /etc/default/transmission ] && . /etc/default/transmission
DAEMON_USER=${DAEMON_USER:-transmission:transmission}
DAEMON_PORT=${DAEMON_PORT:-9091}
DAEMON_ARGS=${DAEMON_ARGS:-"-T --blocklist"}

checkconfig() {
  if [[ "${DAEMON_USER}" == "" ]] ; then
    echo "Please edit /etc/default/transmission"
    echo "You have to specify a user to run transmission as, as we will not run it as root!"
    echo "Modify DAEMON_USER to your needs (you can also add a group, after a colon)"
    return 1
  fi
  if ! $(getent passwd | cut -d ':' -f 1 | grep $( echo "${DAEMON_USER}" | cut -d ':' -f 1 ) -sq) ; then
    echo "Please edit /etc/default/transmission"
    echo "Your user has to exist!"
    return 2
  fi
  unset DAEMON_OUSER
  DAEMON_OUSER=$(echo ${DAEMON_USER} | cut -d ':' -f 1)
  if [[ "${DAEMON_OUSER}" == "root" ]] ; then
    echo "Please edit /etc/default/transmission"
    echo "Do not use root as user!"
    return 3
  fi
  unset DAEMON_GROUP
  echo "${DAEMON_USER}" | grep ':' -sq && DAEMON_GROUP=$( echo ${DAEMON_USER} | cut -d ':' -f 2 )
  if [ -n "${DAEMON_GROUP}" ] && ! $(cut -d ':' -f 1 /etc/group | grep "${DAEMON_GROUP}" -sq) ; then
    echo "Please edit /etc/default/transmission"
    echo "Your group has to exist too!"
    return 4
  fi
  DAEMON_USER_HOME=$(getent passwd | grep ^$( echo "${DAEMON_USER}" | cut -d ':' -f 1 ): | cut -d ':' -f 6)
  return 0
}

checkconfig || exit $?

if [[ "${DAEMON_OUSER}" == "transmission" ]] && [[ -d "${homedir}" ]];then
  chown -R transmission.transmission "${homedir}"
fi

exec /bin/su - "${DAEMON_OUSER}" -s /bin/sh -c "${exec} ${DAEMON_ARGS} -p ${DAEMON_PORT}"
