#!/bin/sh

# This script prepares configuration and run mpd as current user

exec="/usr/bin/mpd"
conffile="/etc/mpd.conf"

if ! [ -f ${conffile} ] ;then
  echo "No ${conffile}, terminating..."
  exit 1
fi

MPD_USER=$(id -un)

if [[ "${MPD_USER}" = "mpd" ]] ; then
  echo "This user do not need this."
  exit 2
fi

MPD_USER_HOME=$(getent passwd | grep ^"${MPD_USER}" | cut -d ':' -f 6)
MPD_USER_CONFIG="${MPD_USER_HOME}/.mpd"
userconffile="${MPD_USER_HOME}/.mpdconf"

if [[ -e "${userconffile}" ]] ; then
  echo "${userconffile} already exists..."
  exit 0
fi

echo "Creating ${userconffile}..."
sed \
  -e 's|/var/lib/mpd|~/.mpd|g' \
  -e "s|^user.*\"mpd\"|user \"${MPD_USER}\"|g" \
  -e 's|^#pid_file|pid_file|g' \
  /etc/mpd.conf > "${userconffile}" || exit 3

mkdir -p "${MPD_USER_CONFIG}"
for file in mpdstate mpd.db mpd.error mpd.log ;do
  echo "Creating ${MPD_USER_CONFIG}/${file}..."
  touch "${MPD_USER_CONFIG}/${file}" || exit 4
done

for dir in music playlists ;do
  echo "Creating ${MPD_USER_CONFIG}/${dir}..."
  mkdir -p "${MPD_USER_CONFIG}/${dir}" || exit 5
done
