#!/bin/sh

# This script prepares configuration and run mpd as user

exec="/usr/bin/deluged"
exec2="/usr/bin/deluge"
homedir="/srv/deluged"

[ -x ${exec} ] || exit 1

unset DELUGED_USER
unset DELUGED_PORT
unset DELUGED_OPTIONS
unset DELUGEUI_START
[ -e /etc/default/deluged ] && . /etc/default/deluged
DELUGED_USER=${DELUGED_USER:-deluge:deluge}
DELUGED_PORT=${DELUGED_PORT:-58846}
DELUGED_OPTIONS=${DELUGED_OPTIONS:-"-L error"}
DELUGEUI_START=${DELUGEUI_START:-NO}

checkconfig() {
  if [[ "${DELUGED_USER}" == "" ]] ; then
    echo "Please edit /etc/default/deluged"
    echo "You have to specify a user to run deluged as, as we will not run it as root!"
    echo "Modify DELUGED_USER to your needs (you can also add a group, after a colon)"
    return 1
  fi
  if ! $(getent passwd | cut -d ':' -f 1 | grep $( echo "${DELUGED_USER}" | cut -d ':' -f 1 ) -sq) ; then
    echo "Please edit /etc/default/deluged"
    echo "Your user has to exist!"
    return 2
  fi
  unset DELUGED_OUSER
  DELUGED_OUSER=$(echo ${DELUGED_USER} | cut -d ':' -f 1)
  if [[ "${DELUGED_OUSER}" == "root" ]] ; then
    echo "Please edit /etc/default/deluged"
    echo "Do not use root as user!"
    return 3
  fi
  unset DELUGED_GROUP
  echo "${DELUGED_USER}" | grep ':' -sq && DELUGED_GROUP=$( echo ${DELUGED_USER} | cut -d ':' -f 2 )
  if [ -n "${DELUGED_GROUP}" ] && ! $(cut -d ':' -f 1 /etc/group | grep "${DELUGED_GROUP}" -sq) ; then
    echo "Please edit /etc/default/deluged"
    echo "Your group has to exist too!"
    return 4
  fi
  DELUGED_USER_HOME=$(getent passwd | grep ^$( echo "${DELUGED_USER}" | cut -d ':' -f 1 ): | cut -d ':' -f 6)
  return 0
}

checkconfig || exit $?

if [[ "${DELUGED_OUSER}" == "deluge" ]] && [[ -d "${homedir}" ]];then
  chown -R deluge.deluge "${homedir}"
fi

if [[ "$1" = "--ui" ]] ;then
  sleep 1
  exec /bin/su - "${DELUGED_OUSER}" -s /bin/sh -c "${exec2} ${DELUGEUI_OPTS}"
else
  exec /bin/su - "${DELUGED_OUSER}" -s /bin/sh -c "${exec} -d -p ${DELUGED_PORT} ${DELUGED_OPTIONS}"
fi
