#! /bin/sh
# Updates the giomodule.cache in /usr/lib*/gio/modules

umask 022

# Get the machine type from uname:
host=$(uname -m)
moduledir=/usr/lib/gio/modules

case "${host}" in
  s390x*|x86_64*)
   if [ -d /usr/lib64/gio/modules ] ;then
     moduledir=/usr/lib64/gio/modules
   fi
   if [ -x /usr/bin/gio-querymodules-64 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating giomodule.cache for ${host} arch:"
       echo "  /usr/bin/gio-querymodules-64 ${moduledir}"
     fi
     /usr/bin/gio-querymodules-64 ${moduledir}
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating giomodule.cache for ${host} arch:"
       echo "  /usr/bin/gio-querymodules ${moduledir}"
     fi
     /usr/bin/gio-querymodules ${moduledir}
   fi
   ;;
  *)
   if [ -x /usr/bin/gio-querymodules-32 ]; then
     if [ "$1" = "--verbose" ]; then
       echo "Updating giomodule.cache for ${host} arch:"
       echo "  /usr/bin/gio-querymodules-32 ${moduledir}"
     fi
     /usr/bin/gio-querymodules-32 ${moduledir}
   else
     if [ "$1" = "--verbose" ]; then
       echo "Updating giomodule.cache for ${host} arch:"
       echo "  /usr/bin/gio-querymodules ${moduledir}"
     fi
     /usr/bin/gio-querymodules ${moduledir}
   fi
   ;;
esac

