#!/bin/sh
#
# ypbind-domain
#
# description: This is part of former ypbind init script, which is used 
#              to setup proper domainname before starting ypbind daemon 
#              itself. If $NISDOMAIN is not defined, it reads config file. 
#

OTHER_YPBIND_OPTS=""

DOMAINNAME=`domainname`
if [ "$DOMAINNAME" = "(none)" -o "$DOMAINNAME" = "" ]; then
    echo -n $"Setting NIS domain: "
    if [ -n "$NISDOMAIN" ]; then
	domainname $NISDOMAIN
    else # See if the domain is set in config file
	NISDOMAIN=`awk '{ if ($1 == "domain") {print $2; exit} }' /etc/yp.conf`
	if [ -n "$NISDOMAIN" ]; then
            domainname $NISDOMAIN
	else
            logger -t ypbind $"domain not found"
        fi
    fi
fi

echo 

