.\" Copyright (C) 2010 Hicham HAOUARI <hicham@fedoraproject.org>
.\" 
.\" This package is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH pulseaudio-equalizer 1  "January 03, 2011"
.SH NAME
pulseaudio-equalizer \- commandline interface to pulseaudio-equalizer-gtk
.SH SYNOPSIS
.B pulseaudio-equalizer
[option]
.SH DESCRIPTION
.B WARNING :
This is for internal use by the pulseaudio-equalizer-gtk interface.
Use for debugging/troubleshooting purposes only.
.SH OPTIONS (current session):
.TP
enable
enable the equalizer
.TP
disable
disable the equalizer
.TP
toggle
enable/disable the equalizer
.SH OPTIONS (persistent):
.TP
enable-config
enable the equalizer configuration
.TP
disable-config
disable the equalizer configuration
.SH OPTIONS (all):
.TP
debug
run equalizer diagnostics
.TP
log
show current equalizer log
.TP
status
show current equalizer status
.SH AUTHOR
Conn O'Griofa <connogriofa AT gmail DOT com>

This manual page was written by Hicham HAOUARI <hicham@fedoraproject.org>,
for the Fedora project (but may be used by others).
.SH BUGS
Please report bugs to https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=pulseaudio-equalizer
.SH SEE ALSO
.B
pulseaudio-equalizer-gtk(1)
